/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  utente
 * Created: 20-mag-2016
 */

CREATE TABLE UserTable (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(32),
    surname VARCHAR(32),
    username VARCHAR(32),
    password VARCHAR(32),
    money DOUBLE PRECISION,
    isSeller BOOLEAN
);

CREATE TABLE ItemTable (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sellerId INTEGER,
    FOREIGN KEY (sellerId) REFERENCES UserTable(id),
    name VARCHAR(32),
    imgName VARCHAR(32),
    imgAlt VARCHAR(32),
    imgHeight INTEGER,
    imgWidth INTEGER,
    amount INTEGER,
    price DOUBLE PRECISION
);

INSERT INTO UserTable (id, name, surname, username, password, money, isSeller)
VALUES (default, 'Maurizio', 'Santini', 'mausan71', 'customer1', 0.0, false);

INSERT INTO UserTable (id, name, surname, username, password, money, isSeller)
VALUES (default, 'Demetra', 'Fini', 'demfi89', 'customer2', 0.0, false);

INSERT INTO UserTable (id, name, surname, username, password, money, isSeller)
VALUES (default, 'Enrico', 'Righi', 'enri75', 'seller1', 2000.0, true);

INSERT INTO UserTable (id, name, surname, username, password, money, isSeller)
VALUES (default, 'Livia', 'Nave', 'lina83', 'seller1', 2000.0, true);

INSERT INTO ItemTable (id, sellerId, name, imgName, imgAlt, imgHeight, imgWidth, amount, price)
VALUES (default, 3, 'Aspirapolvere', 'aspirapolvere.jpg', 'Foto aspirapolvere', 96, 96, 3, 149.99);

INSERT INTO ItemTable (id, sellerId, name, imgName, imgAlt, imgHeight, imgWidth, amount, price)
VALUES (default, 3, 'Cellulare', 'cellulare.jpg', 'Foto cellulare', 96, 96, 7, 69.99);

INSERT INTO ItemTable (id, sellerId, name, imgName, imgAlt, imgHeight, imgWidth, amount, price)
VALUES (default, 3, 'Matite', 'matite.jpg', 'Foto matite', 96, 96, 5, 19.99);

INSERT INTO ItemTable (id, sellerId, name, imgName, imgAlt, imgHeight, imgWidth, amount, price)
VALUES (default, 4, 'Scarpe', 'scarpe.jpg', 'Foto scarpe', 96, 96, 4, 99.99);

INSERT INTO ItemTable (id, sellerId, name, imgName, imgAlt, imgHeight, imgWidth, amount, price)
VALUES (default, 4, 'Tagliaerba', 'tagliaerba.jpg', 'Foto tagliaerba', 96, 96, 2, 54.90);